apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu 
    environment: dev
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      